{'name': 'CRM Company Stages',
 'summary': 'Company-specific CRM pipeline stages, including empty columns',
 'version': '19.0.1.0.0',
 'category': 'Sales/CRM',
 'author': 'Ranvals Software',
 'maintainer': 'Ranvals Software',
 'license': 'LGPL-3',
 'website': 'https://www.odooranvals.com',
 'support': 'info@ranvals.com',
 'price': 9.99,
 'currency': 'EUR',
 'depends': ['crm'],
 'data': ['security/crm_stage_security.xml',
          'views/crm_stage_views.xml',
          'views/crm_lead_views.xml'],
 'images': ['static/description/cover.png'],
 'pre_init_hook': 'pre_init_hook',
 'installable': True,
 'application': False,
 'auto_install': False}
